# **NumPY**

In [2]:
import numpy as np

#### Bsic Array Creation

In [7]:
arr = np.array([1,2,3,4])
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1, 2, 3, 4])

In [6]:
a = [1,2,3,4]
print(type(a))
a

<class 'list'>


[1, 2, 3, 4]

In [10]:
a = np.array([1,2,3,"hello"])
print(type(a))
a

<class 'numpy.ndarray'>


array(['1', '2', '3', 'hello'], dtype='<U21')

In [12]:
l = [[1,2,3], [4,5,6], [7,8,9]]
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Array Generation Function

In [14]:
arr = np.arange(1,11,2)   # range (1 to 10 with 2 gap)
arr

array([1, 3, 5, 7, 9])

In [16]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [18]:
arr = np.zeros((6,6)) #matrix to zeroes [6,6]
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
arr = np.linspace(1,5,10) #Provides equal distance element between generated elements
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

#### Random Generation Function

In [ ]:
np.random.rand(10) # Normalization (When all the values are comes between 0 and 1) statistics

array([0.68733165, 0.41379101, 0.52584467, 0.72490021, 0.46223698,
       0.07966978, 0.00387448, 0.90854842, 0.47142718, 0.79414898])

In [ ]:
np.random.randn(10) #Standardization (When ramdom number comes between -3 to 3)

array([ 2.56055198, -1.49735327, -0.92380767,  0.63024136,  2.4274299 ,
       -0.55221414,  0.07115159,  0.15113595, -0.42292627,  1.0560914 ])

In [ ]:
np.random.randint(10,20,10) # first two (10,20) range 10 is limit 

array([14, 11, 18, 10, 19, 18, 17, 17, 16, 13], dtype=int32)

#### Array Attributes

In [44]:
arr = np.array([[1,2,3,],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr.shape

(3, 3)

In [45]:
arr.size

9

In [46]:
arr.dtype

dtype('int64')

#### Array Methods

In [47]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arr.min()

np.int64(1)

In [49]:
arr.max()

np.int64(9)

In [50]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr,axis = 0) #addition of columns (i.e Y-axis or 0-axis) ie, y=0

array([12, 15, 18])

In [ ]:
np.sum(arr,axis = 1) #addition of rows (i.e x-axis or 1-axis) i.e, x=1

array([ 6, 15, 24])

In [56]:
arr.argmax()

np.int64(8)

In [57]:
arr.argmin()

np.int64(0)

#### Reshaping and Resizing

In [58]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr.reshape(6,5) #6(rows), 5(columns)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])