# **Array indexing**

In [1]:
import numpy as np

#### NUMPY INDEXING AND SLICING OF VECTORS

In [4]:
arr = np.arange(10,21)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
arr[6]  #accessing the element

np.int64(16)

In [8]:
arr[1:6]    #slicing is just like list in python

array([11, 12, 13, 14, 15])

In [9]:
arr[3::2]

array([13, 15, 17, 19])

#### NUMPY INDEXING AND SLICING OF A MATRIX 

In [10]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[0]  # singel number will target rows of matrix

array([1, 2, 3, 4, 5])

In [27]:
arr[:,0:1] #Row(all),column(one)

array([[ 1],
       [ 6],
       [11],
       [16],
       [21],
       [26]])

In [ ]:
arr[3,0]    #arr[row,column] #3rd row 0th column

np.int64(16)

In [17]:
arr[0:2,1:4] #slicing of Matrix

array([[2, 3, 4],
       [7, 8, 9]])

In [19]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

#### BOOLEAN INDEXING

In [29]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [30]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [31]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])