# ARRAY OPERATIONS

In [72]:
import numpy as np

#### Arithmatic operations

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [8]:
arr2 = a1+a2    #Number of elements nust be same in both array 
arr3 = a1-a2
arr4 = a1*a2
arr5 = a1/a2
arr6 = a1**a2
print(arr2)
print(arr3)
print(arr4)
print(arr5)
print(arr6)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[      1     128    6561  262144 9765625]


#### Broadcasting

In [10]:
l = [10,20,30,40]
arr = np.array(l)

In [11]:
arr + 10

array([20, 30, 40, 50])

In [17]:
arr_matrix = np.arange(1,26).reshape(5,5)
arr_matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [24]:
arr_matrix *10

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250]])

#### Deep and Shallow Copy

In [31]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [32]:
slice = a[:5]
slice = slice*10    # slicing array will create a seprerate location in RAM but list in python can't do it, list change when we make any small change in it
slice

array([10, 20, 30, 40, 50])

In [33]:
a   #This is shallow coppy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a [4:6] * 10    # Their will no change in main array
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a
b = a
#b = a.coppy() #! If you use a.coppy() then nohing will change in main array because it is copy of main array
b[0] = 99

In [ ]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a   # Now it will change main array because it will only works on slicing #! only slicing will take separate spabe in RAM

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

#### Matrix operations 

In [45]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [47]:
A

array([[1, 2],
       [3, 4]])

In [48]:
B

array([[5, 6],
       [7, 8]])

In [ ]:
A @ B   #@ for matrix multiplication

array([[19, 22],
       [43, 50]])

In [50]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [51]:
A.T #Transpose

array([[1, 3],
       [2, 4]])

## Advance Array Manupulation

#### Stacking Array

In [ ]:
a = np.array([1,2,3,4])     # stacking of array means combining of array and create a new one
b = np.array([5,6,7,8])

In [60]:
np.stack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.vstack((a,b))    #verticle-stack

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.hstack((a,b))    #horizontal-stack

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.column_stack((a,b))  # column_stack converts 1d array into 2d array

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

#### Spilitting Array

In [69]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [70]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [73]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]