# Exercise


### Valid Sudoku

In [1]:
import numpy as np

In [3]:
s = np.array([
    [5, 3, 4,  6, 7, 8,  9, 1, 2],
    [6, 7, 2,  1, 9, 5,  3, 4, 8],
    [1, 9, 8,  3, 4, 2,  5, 6, 7],
    
    [8, 5, 9,  7, 6, 1,  4, 2, 3],
    [4, 2, 6,  8, 5, 3,  7, 9, 1],
    [7, 1, 3,  9, 2, 4,  8, 5, 6],
    
    [9, 6, 1,  5, 3, 7, 2,  8, 4],
    [2, 8, 7,  4, 1, 9, 6,  3, 5],
    [3, 4, 5,  2, 8, 6, 1,  7, 9]
])

In [ ]:
np.sum(s,axis = 1)  # y axis

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [ ]:
np.sum(s,axis = 0)  # x axis

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [ ]:
np.sum(s, axis=0).reshape(-1, 1)    #same x axis sum

array([[45],
       [45],
       [45],
       [45],
       [45],
       [45],
       [45],
       [45],
       [45]])

In [7]:
np.sum(s, axis=0).reshape(1, -1)

array([[45, 45, 45, 45, 45, 45, 45, 45, 45]])

In [ ]:
b = np.sum(s, axis = 1) #Another way to check
b == 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [10]:
b = np.sum(s, axis = 1)
for i in b:
    if i != 45:
        print("Suboku is not valid")
        break
else:
    print("For rows it is valid")

For rows it is valid


In [11]:
c = np.sum(s, axis = 0)
for i in c:
    if i != 45:
        print("Suboku is not valid")
        break
else:
    print("For columns it is valid")

For columns it is valid


In [ ]:
for i in range(0,9,3):      # to print all 3X3 blocks
    for j in range(0,9,3):
        n = (s[i:i+3,j:j+3])
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [49]:
import numpy as np

# column : [Age, Math Marks, Science Marks]
data  = np.array([
    [18, 85, 78],   #Student 1
    [19, 92, 88],   #Student 2
    [17, 76, 95],   #Student 3
    [18, 65, 70],   #Student 4
    [20, 90, 85]    #Student 5
])

In [21]:
# get the shape of the matrix
data.shape

(5, 3)

In [28]:
# find the average age of students
np.mean(data[:,0])

np.float64(18.4)

In [34]:
# Extract the Maths marks of all students
print(data[:, 1].reshape(-1, 1))

[[85]
 [92]
 [76]
 [65]
 [90]]


In [35]:
# find highest Science Marks
np.max(data[:,2])

np.int64(95)

In [38]:
# get details od the student who scored more than 90 in Maths

data[data[:,1] > 90]

array([[19, 92, 88]])

In [76]:
# Increase maths marks by 5

data[:,1] += 5
data

array([[ 18, 100,  78],
       [ 19, 107,  88],
       [ 17,  91,  95],
       [ 18,  80,  70],
       [ 20, 105,  85]])

In [ ]:
# Find how many students are younger than 19

len(data[data[:,0] < 19])


3

In [72]:
# calculate the average marks in each subject (column-wise mean)
np.mean(data[:,1:], axis= 0)

array([91.6, 83.2])

In [85]:
# Get data of student who scored at least 80 in both exams

data[(data[:, 1] >= 80) & (data[:, 2] >= 80)]

array([[ 19, 107,  88],
       [ 17,  91,  95],
       [ 20, 105,  85]])

In [86]:
data

array([[ 18, 100,  78],
       [ 19, 107,  88],
       [ 17,  91,  95],
       [ 18,  80,  70],
       [ 20, 105,  85]])

In [87]:
# Replace all science marks < 75 with 0

data[:,2][data[:,2] < 75] = 0
data

array([[ 18, 100,  78],
       [ 19, 107,  88],
       [ 17,  91,  95],
       [ 18,  80,   0],
       [ 20, 105,  85]])